/*CD LAB EX.NO.6 TOP DOWN PARSING */
#include <stdio.h>
#include<string.h>
#include <stdlib.h>
#define MAX 50
int n,np[26]={0},nin;
char in[MAX],pd[26][MAX][MAX];
int check(char *cur)
{
    int i;
    for(i=0;cur[i];i++)
    {
        int index=cur[i]-'A';
        if(isupper(cur[i]))
        {
            for(int j=0;j<np[index];j++)
                {
                    char temp[MAX];
                        int a=0;
                        for(int x=0;x<i;x++)
                            temp[a++]=cur[x];
                    if(strcmp(pd[index][j],"#"))
                        for(int x=0;pd[index][j][x];x++)
                            temp[a++]=pd[index][j][x];
                        for(int x=i+1;cur[x];x++)
                            temp[a++]=cur[x];
                        temp[a]=0;
                        printf("\n%s",temp);
                        if(i<=nin&&check(temp))return 1;
                }
                return 0;
        }
        else if(in[i]!=cur[i])return 0;
    }
    return i==nin;

}
int main()
{
    int index;
    char parent[1];
    printf("(Input the Grammar)Enter no.of productions :");
    scanf("%d",&n);
    printf("Enter the productions (consider UPPERCASE ALPHABET as non-terminal, epsilon as # symbol):");
    for(int i=0;i<n;i++){
    scanf("%s",in);
    index=in[0]-'A';
    strcpy(pd[index][np[index]++],in+2);
    }
    printf("Enter a string to check and parse top down :");
    scanf("%s",in);
    nin=strlen(in);
    printf("Enter initial production non-terminal :");
    scanf("%s",parent);
    if(check(parent))
        printf("\nThe string %s can be generated by this grammar",in);
    else
        printf("\nThe string %s can not be generated by this grammar",in);
    return 0;
}
/*
TESTCASE 0:
(Input the Grammar)Enter no.of productions :4
Enter the productions (consider UPPERCASE ALPHABET as non-terminal, epsilon as # symbol):S=AaBb
A=abB
B=ba
A=bbA
Enter a string to check and parse top down :bbabbaabab
Enter initial production non-terminal :S

AaBb
abBaBb
bbAaBb
bbabBaBb
bbabbaaBb
bbabbaabab
The string bbabbaabab can be generated by this grammar
Process returned 0 (0x0)   execution time : 95.195 s
Press any key to continue.




TESTCASE 1:
(Input the Grammar)Enter no.of productions :10
Enter the productions (consider UPPERCASE ALPHABET as non-terminal, epsilon as - symbol):E=TZ
Z=+TZ
Z=#
T=FY
Y=*FY
Y=#
F=a
F=b
F=c
F=(E)
Enter a string to check and parse top down :a+(a+b)*(b+c)*(c+a)+a*b*(a+b+c)
Enter initial production non-terminal :E

TZ
FYZ
aYZ
a*FYZ
aZ
a+TZ
a+FYZ
a+aYZ
a+bYZ
a+cYZ
a+(E)YZ
a+(TZ)YZ
a+(FYZ)YZ
a+(aYZ)YZ
a+(a*FYZ)YZ
a+(aZ)YZ
a+(a+TZ)YZ
a+(a+FYZ)YZ
a+(a+aYZ)YZ
a+(a+bYZ)YZ
a+(a+b*FYZ)YZ
a+(a+bZ)YZ
a+(a+b+TZ)YZ
a+(a+b)YZ
a+(a+b)*FYZ
a+(a+b)*aYZ
a+(a+b)*bYZ
a+(a+b)*cYZ
a+(a+b)*(E)YZ
a+(a+b)*(TZ)YZ
a+(a+b)*(FYZ)YZ
a+(a+b)*(aYZ)YZ
a+(a+b)*(bYZ)YZ
a+(a+b)*(b*FYZ)YZ
a+(a+b)*(bZ)YZ
a+(a+b)*(b+TZ)YZ
a+(a+b)*(b+FYZ)YZ
a+(a+b)*(b+aYZ)YZ
a+(a+b)*(b+bYZ)YZ
a+(a+b)*(b+cYZ)YZ
a+(a+b)*(b+c*FYZ)YZ
a+(a+b)*(b+cZ)YZ
a+(a+b)*(b+c+TZ)YZ
a+(a+b)*(b+c)YZ
a+(a+b)*(b+c)*FYZ
a+(a+b)*(b+c)*aYZ
a+(a+b)*(b+c)*bYZ
a+(a+b)*(b+c)*cYZ
a+(a+b)*(b+c)*(E)YZ
a+(a+b)*(b+c)*(TZ)YZ
a+(a+b)*(b+c)*(FYZ)YZ
a+(a+b)*(b+c)*(aYZ)YZ
a+(a+b)*(b+c)*(bYZ)YZ
a+(a+b)*(b+c)*(cYZ)YZ
a+(a+b)*(b+c)*(c*FYZ)YZ
a+(a+b)*(b+c)*(cZ)YZ
a+(a+b)*(b+c)*(c+TZ)YZ
a+(a+b)*(b+c)*(c+FYZ)YZ
a+(a+b)*(b+c)*(c+aYZ)YZ
a+(a+b)*(b+c)*(c+a*FYZ)YZ
a+(a+b)*(b+c)*(c+aZ)YZ
a+(a+b)*(b+c)*(c+a+TZ)YZ
a+(a+b)*(b+c)*(c+a)YZ
a+(a+b)*(b+c)*(c+a)*FYZ
a+(a+b)*(b+c)*(c+a)Z
a+(a+b)*(b+c)*(c+a)+TZ
a+(a+b)*(b+c)*(c+a)+FYZ
a+(a+b)*(b+c)*(c+a)+aYZ
a+(a+b)*(b+c)*(c+a)+a*FYZ
a+(a+b)*(b+c)*(c+a)+a*aYZ
a+(a+b)*(b+c)*(c+a)+a*bYZ
a+(a+b)*(b+c)*(c+a)+a*b*FYZ
a+(a+b)*(b+c)*(c+a)+a*b*aYZ
a+(a+b)*(b+c)*(c+a)+a*b*bYZ
a+(a+b)*(b+c)*(c+a)+a*b*cYZ
a+(a+b)*(b+c)*(c+a)+a*b*(E)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(TZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(FYZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(aYZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a*FYZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(aZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+TZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+FYZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+aYZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+bYZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b*FYZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+bZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+TZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+FYZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+aYZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+bYZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+cYZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+c*FYZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+cZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+c+TZ)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+c)YZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+c)*FYZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+c)Z
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+c)+TZ
a+(a+b)*(b+c)*(c+a)+a*b*(a+b+c)
The string a+(a+b)*(b+c)*(c+a)+a*b*(a+b+c) can be generated by this grammar
Process returned 0 (0x0)   execution time : 165.574 s
Press any key to continue.



TESTCASE 2:
(Input the Grammar)Enter no.of productions :10
Enter the productions (consider UPPERCASE ALPHABET as non-terminal, epsilon as # symbol):E=TZ
Z=+TZ
Z=#
T=FY
Y=*FY
Y=#
F=a
F=b
F=c
F=(E)
Enter a string to check and parse top down :a*a+b*b+cc
Enter initial production non-terminal :E

TZ
FYZ
aYZ
a*FYZ
a*aYZ
a*a*FYZ
a*aZ
a*a+TZ
a*a+FYZ
a*a+aYZ
a*a+bYZ
a*a+b*FYZ
a*a+b*aYZ
a*a+b*bYZ
a*a+b*b*FYZ
a*a+b*bZ
a*a+b*b+TZ
a*a+b*b+FYZ
a*a+b*b+aYZ
a*a+b*b+bYZ
a*a+b*b+cYZ
a*a+b*b+c*FYZ
a*a+b*b+cZ
a*a+b*b+c+TZ
a*a+b*b+c
a*a+b*b+(E)YZ
a*a+b*b
a*a+b*cYZ
a*a+b*(E)YZ
a*a+bZ
a*a+b+TZ
a*a+b
a*a+cYZ
a*a+(E)YZ
a*a
a*bYZ
a*cYZ
a*(E)YZ
aZ
a+TZ
a
bYZ
cYZ
(E)YZ
The string a*a+b*b+cc can not be generated by this grammar
Process returned 0 (0x0)   execution time : 59.659 s
Press any key to continue.

*/

/*
 *Logic : Backtracking
 *programmed by Srivishnu GCE Salem
*/
